FROM openjdk:20
MAINTAINER Goncalo Rosa e Tiago Martins
COPY target/Microservico-Gestao-0.0.1-SNAPSHOT.jar Microservico-Gestao-0.0.1-SNAPSHOT.jar
ENTRYPOINT exec java $JAVA_OPTS -jar Microservico-Gestao-0.0.1-SNAPSHOT.jar