FROM openjdk:20
MAINTAINER Goncalo Rosa e Tiago Martins
COPY target/naming-server-0.0.1-SNAPSHOT.jar naming-server-0.0.1-SNAPSHOT.jar
ENTRYPOINT exec java $JAVA_OPTS -jar naming-server-0.0.1-SNAPSHOT.jar